WB0573SK0/SmartAdmin-1.9.6.1-legacy-86d1c1fa398a/DEVELOPER/BS3/RubyOnRails/seed/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'miscellaneous#blank_page'
  # Miscellaneous
  get 'miscellaneous/login',
      to: 'miscellaneous#login',
      as: :miscellaneous_login
  get 'miscellaneous/register',
      to: 'miscellaneous#register',
      as: :miscellaneous_register
  get 'miscellaneous/forgot_password',
      to: 'miscellaneous#forgot_password',
      as: :miscellaneous_forgot_password
  get 'miscellaneous/locked_screen',
      to: 'miscellaneous#locked_screen',
      as: :miscellaneous_locked_screen

  # AJAX
  get 'ajax/email_compose', to: 'ajax#email_compose', as: :ajax_email_compose
  get 'ajax/email_list', to: 'ajax#email_list', as: :ajax_email_list
  get 'ajax/email_opened', to: 'ajax#email_opened', as: :ajax_email_opened
  get 'ajax/email_reply', to: 'ajax#email_reply', as: :ajax_email_reply
  get 'ajax/demo_widget', to: 'ajax#demo_widget', as: :ajax_demo_widget
  get 'ajax/data_list.json', to: 'ajax#data_list', as: :ajax_data_list
  get 'ajax/notify_mail', to: 'ajax#notify_mail', as: :ajax_notify_mail
  get 'ajax/notify_notifications',
      to: 'ajax#notify_notifications',
      as: :ajax_notify_notifications
  get 'ajax/notify_tasks', to: 'ajax#notify_tasks', as: :ajax_notify_tasks

  # Misc methods
  get '/home/set_locale', to: 'home#set_locale', as: :home_set_locale

  # CK editor
  mount Ckeditor::Engine => '/ckeditor'
end

WB0573SK0/SmartAdmin-1.9.6.1-legacy-86d1c1fa398a/DEVELOPER/BS3/RubyOnRails/seed/app/models/application_record.rb
# :nodoc:
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

WB0573SK0/SmartAdmin-1.9.6.1-legacy-86d1c1fa398a/DEVELOPER/BS3/RubyOnRails/seed/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def remember_me
    (super == nil) ? '1' : super
    end
end

WB0573SK0/SmartAdmin-1.9.6.1-legacy-86d1c1fa398a/DEVELOPER/BS3/RubyOnRails/seed/app/controllers/ajax_controller.rb
# AJAX helpers
class AjaxController < ApplicationController
  layout false

  def email_list
  end

  def email_compose
  end

  def email_opened
  end

  def email_reply
  end

  def demo_widget
  end

  def data_list
  end

  def notify_mail
  end

  def notify_notifications
  end

  def notify_tasks
  end
end

WB0573SK0/SmartAdmin-1.9.6.1-legacy-86d1c1fa398a/DEVELOPER/BS3/RubyOnRails/seed/app/controllers/application_controller.rb
# :nodoc:
class ApplicationController < ActionController::Base
  before_filter :set_gettext_locale
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

WB0573SK0/SmartAdmin-1.9.6.1-legacy-86d1c1fa398a/DEVELOPER/BS3/RubyOnRails/seed/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def set_locale
    session[:locale] = params[:locale]
    redirect_to :back
  end
end

WB0573SK0/SmartAdmin-1.9.6.1-legacy-86d1c1fa398a/DEVELOPER/BS3/RubyOnRails/seed/app/controllers/miscellaneous_controller.rb
class MiscellaneousController < ApplicationController
  skip_before_filter :authenticate_user!, only: [:register, :forgot_password]

  def login
    @simulate_no_user = true
  end

  def register
    @simulate_no_user = true
  end

  def forgot_password
    @simulate_no_user = true
  end

  def locked_screen
    @simulate_no_user = true
    @lock_screen = true
  end

  def blank_page
  end
end

WB0573SK0/SmartAdmin-1.9.6.1-legacy-86d1c1fa398a/DEVELOPER/BS3/RubyOnRails/seed/app/helpers/application_helper.rb
# :nodoc:
module ApplicationHelper
  def left_menu
    left_menu_entries(left_menu_content)
  end

  private

  def selected_locale
    locale = FastGettext.locale
    locale_list.detect {|entry| entry[:locale] == locale}
  end

  def locale_list
    [
      {
        flag: 'us',
        locale: 'en',
        name: 'English (US)',
        alt_name: 'United States'
      },
      {
        flag: 'fr',
        locale: 'fr',
        name: 'Français',
        alt_name: 'France'
      },
      {
        flag: 'es',
        locale: 'es',
        name: 'Español',
        alt_name: 'Spanish'
      },
      {
        flag: 'de',
        locale: 'de',
        name: 'Deutsch',
        alt_name: 'German'
      },
      {
        flag: 'jp',
        locale: 'ja',
        name: '日本語',
        alt_name: 'Japan'
      },
      {
        flag: 'cn',
        locale: 'zh',
        name: '中文',
        alt_name: 'China'
      },
      {
        flag: 'it',
        locale: 'it',
        name: 'Italiano',
        alt_name: 'Italy'
      },
      {
        flag: 'pt',
        locale: 'pt',
        name: 'Portugal',
        alt_name: 'Portugal'
      },
      {
        flag: 'ru',
        locale: 'ru',
        name: 'Русский язык',
        alt_name: 'Russia'
      },
      {
        flag: 'kr',
        locale: 'kr',
        name: '한국어',
        alt_name: 'Korea'
      },
    ]
  end

  def left_menu_entries(entries = [])
    output = ''
    entries.each do |entry|
      children_selected = entry[:children] &&
        entry[:children].any? {|child| current_page?(child[:href]) }
      entry_selected =  current_page?(entry[:href])
      li_class =
      case
        when children_selected
          'open'
        when entry_selected
          'active'
      end
      output +=
        content_tag(:li, class: li_class) do
          subentry = ''
          subentry +=
            link_to entry[:href], title: entry[:title], class: entry[:class], target: entry[:target] do
              link_text = ''
              link_text += entry[:content].html_safe
              if entry[:children]
                if children_selected
                  link_text += '<b class="collapse-sign"><em class="fa fa-minus-square-o"></em></b>'
                else
                  link_text += '<b class="collapse-sign"><em class="fa fa-plus-square-o"></em></b>'
                end
              end

              link_text.html_safe
            end
          if entry[:children]
            if children_selected
              ul_style = 'display: block'
            else
              ul_style = ''
            end
            subentry +=
              "<ul style='#{ul_style}'>" +
                left_menu_entries(entry[:children]) +
                "</ul>"
          end

          subentry.html_safe
        end
    end
    output.html_safe
  end

  def left_menu_content
    [
      {
        href: root_path,
        title: _('blank'),
        content: "<i class='fa fa-lg fa-fw fa-home'></i> <span class='menu-item-parent'>" + _('Blank') + "</span>",
      },
    ]
  end

end

WB0573SK0/SmartAdmin-1.9.6.1-legacy-86d1c1fa398a/DEVELOPER/BS3/RubyOnRails/seed/app/views/miscellaneous/blank_page.html.erb
<% content_for :ribbon do %>
  <!-- RIBBON -->
  <div id="ribbon">

    <!-- breadcrumb -->
    <ol class="breadcrumb">
      <li>Home</li>
      <li>Blank</li>
    </ol>
    <!-- end breadcrumb -->

    <!-- You can also add more buttons to the
    ribbon for further usability

    Example below:

    <span class="ribbon-button-alignment pull-right" style="margin-right:25px">
      <a href="#" id="search" class="btn btn-ribbon hidden-xs" data-title="search"><i class="fa fa-grid"></i> Change Grid</a>
      <span id="add" class="btn btn-ribbon hidden-xs" data-title="add"><i class="fa fa-plus"></i> Add</span>
      <button id="search" class="btn btn-ribbon" data-title="search"><i class="fa fa-search"></i> <span class="hidden-mobile">Search</span></button>
    </span> -->

  </div>
  <!-- END RIBBON -->
<% end %>

			<!-- #MAIN CONTENT -->

				
				<!-- col -->
				<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
					<h1 class="page-title txt-color-blueDark">
						
						<!-- PAGE HEADER -->
						<i class="fa-fw fa fa-home"></i> 
							Page Header 
						<span>>  
							Subtitle
						</span>
					</h1>
				</div>
				<!-- end col -->
				

			<!-- end row -->
			
			<!-- END #MAIN CONTENT -->
<% content_for :scripts do %>
// Empty
<% end %>

WB0573SK0/SmartAdmin-1.9.6.1-legacy-86d1c1fa398a/DEVELOPER/BS3/RubyOnRails/seed/app/views/miscellaneous/forgot_password.html.erb
<% content_for :html_id, "extr-page" %>
<% content_for :body_class, "animated fadeInDown" %>
<% content_for :top_right do %>
  <span id="extr-page-header-space"> <span class="hidden-mobile hiddex-xs">Need an account?</span>
    <%= link_to 'Create account', miscellaneous_register_path, class: 'btn btn-danger' %>
  </span>
<% end %>
<!-- MAIN CONTENT -->
<div id="content" class="container">

  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-7 col-lg-8 hidden-xs hidden-sm">
      <h1 class="txt-color-red login-header-big">SmartAdmin</h1>
      <div class="hero">

        <div class="pull-left login-desc-box-l">
          <h4 class="paragraph-header">It's Okay to be Smart. Experience the simplicity of SmartAdmin, everywhere you go!</h4>
          <div class="login-app-icons">
            <a href="javascript:void(0);" class="btn btn-danger btn-sm">Frontend Template</a>
            <a href="javascript:void(0);" class="btn btn-danger btn-sm">Find out more</a>
          </div>
        </div>

        <%= image_tag 'demo/iphoneview.png', class: 'pull-right display-image', alt: '', style: 'width:210px' %>

      </div>

      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
          <h5 class="about-heading">About SmartAdmin - Are you up to date?</h5>
          <p>
            Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa.
          </p>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
          <h5 class="about-heading">Not just your average template!</h5>
          <p>
            Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi voluptatem accusantium!
          </p>
        </div>
      </div>

    </div>
    <div class="col-xs-12 col-sm-12 col-md-5 col-lg-4">
      <div class="well no-padding">
        <form action="login.html" id="login-form" class="smart-form client-form">
          <header>
            Forgot Password
          </header>

          <fieldset>

            <section>
              <label class="label">Enter your email address</label>
              <label class="input"> <i class="icon-append fa fa-envelope"></i>
                <input type="email" name="email">
                <b class="tooltip tooltip-top-right"><i class="fa fa-envelope txt-color-teal"></i> Please enter email address for password reset</b></label>
            </section>
            <section>
              <span class="timeline-seperator text-center text-primary"> <span class="font-sm">OR</span></span>
            </section>
            <section>
              <label class="label">Your Username</label>
              <label class="input"> <i class="icon-append fa fa-user"></i>
                <input type="text" name="username">
                <b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> Enter your username</b> </label>
              <div class="note">
                <a href="login.html">I remembered my password!</a>
              </div>
            </section>

          </fieldset>
          <footer>
            <button type="submit" class="btn btn-primary">
              <i class="fa fa-refresh"></i> Reset Password
            </button>
          </footer>
        </form>

      </div>

      <h5 class="text-center"> - Or sign in using -</h5>

              <ul class="list-inline text-center">
                <li>
                  <a href="javascript:void(0);" class="btn btn-primary btn-circle"><i class="fa fa-facebook"></i></a>
                </li>
                <li>
                  <a href="javascript:void(0);" class="btn btn-info btn-circle"><i class="fa fa-twitter"></i></a>
                </li>
                <li>
                  <a href="javascript:void(0);" class="btn btn-warning btn-circle"><i class="fa fa-linkedin"></i></a>
                </li>
              </ul>

    </div>
  </div>
</div>

WB0573SK0/SmartAdmin-1.9.6.1-legacy-86d1c1fa398a/DEVELOPER/BS3/RubyOnRails/seed/app/views/miscellaneous/locked_screen.html.erb
<% content_for :html_id, "lock-page" %>
<!-- MAIN CONTENT -->

<form class="lockscreen animated flipInY" action="index.html">
  <div class="logo">
    <h1 class="semi-bold"><%= image_tag 'logo-o.png', alt: '' %> SmartAdmin</h1>
  </div>
  <div>
    <%= image_tag 'avatars/sunny-big.png', alt: '', width: '120', height: '120' %>
    <div>
      <h1><i class="fa fa-user fa-3x text-muted air air-top-right hidden-mobile"></i>John Doe <small><i class="fa fa-lock text-muted"></i> &nbsp;Locked</small></h1>
      <p class="text-muted">
        <a href="mailto:simmons@smartadmin">john.doe@smartadmin.com</a>
      </p>

      <div class="input-group">
        <input class="form-control" type="password" placeholder="Password">
        <div class="input-group-btn">
          <button class="btn btn-primary" type="submit">
            <i class="fa fa-key"></i>
          </button>
        </div>
      </div>
      <p class="no-margin margin-top-5">
        Logged as someone else? <a href="login.html"> Click here</a>
      </p>
    </div>

  </div>
  <p class="font-xs margin-top-5">
    Copyright SmartAdmin 2014-2020.

  </p>
</form>

WB0573SK0/SmartAdmin-1.9.6.1-legacy-86d1c1fa398a/DEVELOPER/BS3/RubyOnRails/seed/app/views/miscellaneous/login.html.erb
<% content_for :html_id, "extr-page" %>
<% content_for :body_class, "animated fadeInDown" %>
<% content_for :top_right do %>
  <span id="extr-page-header-space"> <span class="hidden-mobile hiddex-xs">Need an account?</span> <a href="register.html" class="btn btn-danger">Create account</a> </span>
<% end %>
<!-- MAIN CONTENT -->
<div id="content" class="container">

  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-7 col-lg-8 hidden-xs hidden-sm">
      <h1 class="txt-color-red login-header-big">SmartAdmin</h1>
      <div class="hero">

        <div class="pull-left login-desc-box-l">
          <h4 class="paragraph-header">It's Okay to be Smart. Experience the simplicity of SmartAdmin, everywhere you go!</h4>
          <div class="login-app-icons">
            <a href="javascript:void(0);" class="btn btn-danger btn-sm">Frontend Template</a>
            <a href="javascript:void(0);" class="btn btn-danger btn-sm">Find out more</a>
          </div>
        </div>

        <%= image_tag 'demo/iphoneview.png', class: 'pull-right display-image', alt: '', style: 'width:210px' %>

      </div>

      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
          <h5 class="about-heading">About SmartAdmin - Are you up to date?</h5>
          <p>
            Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa.
          </p>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
          <h5 class="about-heading">Not just your average template!</h5>
          <p>
            Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi voluptatem accusantium!
          </p>
        </div>
      </div>

    </div>
    <div class="col-xs-12 col-sm-12 col-md-5 col-lg-4">
      <div class="well no-padding">
        <form action="index.html" id="login-form" class="smart-form client-form">
          <header>
            Sign In
          </header>

          <fieldset>

            <section>
              <label class="label">E-mail</label>
              <label class="input"> <i class="icon-append fa fa-user"></i>
                <input type="email" name="email">
                <b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> Please enter email address/username</b></label>
            </section>

            <section>
              <label class="label">Password</label>
              <label class="input"> <i class="icon-append fa fa-lock"></i>
                <input type="password" name="password">
                <b class="tooltip tooltip-top-right"><i class="fa fa-lock txt-color-teal"></i> Enter your password</b> </label>
              <div class="note">
                <a href="forgotpassword.html">Forgot password?</a>
              </div>
            </section>

            <section>
              <label class="checkbox">
                <input type="checkbox" name="remember" checked="">
                <i></i>Stay signed in</label>
            </section>
          </fieldset>
          <footer>
            <button type="submit" class="btn btn-primary">
              Sign in
            </button>
          </footer>
        </form>

      </div>

      <h5 class="text-center"> - Or sign in using -</h5>

        <ul class="list-inline text-center">
          <li>
            <a href="javascript:void(0);" class="btn btn-primary btn-circle"><i class="fa fa-facebook"></i></a>
          </li>
          <li>
            <a href="javascript:void(0);" class="btn btn-info btn-circle"><i class="fa fa-twitter"></i></a>
          </li>
          <li>
            <a href="javascript:void(0);" class="btn btn-warning btn-circle"><i class="fa fa-linkedin"></i></a>
          </li>
        </ul>

    </div>
  </div>
</div>


<% content_for :scripts do %>
  <script type="text/javascript">
    runAllForms();

    $(function() {
      // Validation
      $("#login-form").validate({
        // Rules for form validation
        rules : {
          email : {
            required : true,
            email : true
          },
          password : {
            required : true,
            minlength : 3,
            maxlength : 20
          }
        },

        // Messages for form validation
        messages : {
          email : {
            required : 'Please enter your email address',
            email : 'Please enter a VALID email address'
          },
          password : {
            required : 'Please enter your password'
          }
        },

        // Do not change code below
        errorPlacement : function(error, element) {
          error.insertAfter(element.parent());
        }
      });
    });
  </script>
<% end %>