WB0573SK0/SmartAdmin-1.9.6.1-legacy-86d1c1fa398a/DEVELOPER/BS3/RubyOnRails/full/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#analytics'
  get 'dashboards/dashboard-social',
      to: 'dashboard#social',
      as: :dashboard_social

  # Smartadmin intel
  get 'smartadmin_intel/app_layouts',
      to: 'smartadmin_intel#app_layouts',
      as: :smartadmin_intel_app_layouts
  get 'smartadmin_intel/app_settings',
      to: 'smartadmin_intel#app_settings',
      as: :smartadmin_intel_app_settings
  get 'smartadmin_intel/prebuilt_skins',
      to: 'smartadmin_intel#prebuilt_skins',
      as: :smartadmin_intel_prebuilt_skins
  get 'outlook/inbox', to: 'outlook#inbox', as: :outlook_inbox

  # AJAX
  get 'ajax/email_compose', to: 'ajax#email_compose', as: :ajax_email_compose
  get 'ajax/email_list', to: 'ajax#email_list', as: :ajax_email_list
  get 'ajax/email_opened', to: 'ajax#email_opened', as: :ajax_email_opened
  get 'ajax/email_reply', to: 'ajax#email_reply', as: :ajax_email_reply
  get 'ajax/demo_widget', to: 'ajax#demo_widget', as: :ajax_demo_widget
  get 'ajax/data_list.json', to: 'ajax#data_list', as: :ajax_data_list
  get 'ajax/notify_mail', to: 'ajax#notify_mail', as: :ajax_notify_mail
  get 'ajax/notify_notifications',
      to: 'ajax#notify_notifications',
      as: :ajax_notify_notifications
  get 'ajax/notify_tasks', to: 'ajax#notify_tasks', as: :ajax_notify_tasks

  # Graphs
  get 'graphs/flot_chart', to: 'graphs#flot_chart', as: :graphs_flot_chart
  get 'graphs/morris_charts',
      to: 'graphs#morris_charts',
      as: :graphs_morris_charts
  get 'graphs/sparklines', to: 'graphs#sparklines', as: :graphs_sparklines
  get 'graphs/easy_pie_charts',
      to: 'graphs#easy_pie_charts',
      as: :graphs_easy_pie_charts
  get 'graphs/dygraphs', to: 'graphs#dygraphs', as: :graphs_dygraphs
  get 'graphs/chart_js', to: 'graphs#chart_js', as: :graphs_chart_js
  get 'graphs/highchart_table',
      to: 'graphs#highchart_table',
      as: :graphs_highchart_table

  # Tables
  get 'tables/normal_tables',
      to: 'tables#normal_tables',
      as: :tables_normal_tables
  get 'tables/data_tables', to: 'tables#data_tables', as: :tables_data_tables
  get 'tables/jquery_grid', to: 'tables#jquery_grid', as: :tables_jquery_grid

  # Forms
  get 'forms/smart_form_elements',
      to: 'forms#smart_form_elements',
      as: :forms_smart_form_elements
  get 'forms/smart_form_layouts',
      to: 'forms#smart_form_layouts',
      as: :forms_smart_form_layouts
  get 'forms/smart_form_validations',
      to: 'forms#smart_form_validations',
      as: :forms_smart_form_validations
  get 'forms/bootstrap_form_elements',
      to: 'forms#bootstrap_form_elements',
      as: :forms_bootstrap_form_elements
  get 'forms/bootstrap_form_validation',
      to: 'forms#bootstrap_form_validation',
      as: :forms_bootstrap_form_validation
  get 'forms/form_plugins', to: 'forms#form_plugins', as: :forms_form_plugins
  get 'forms/wizards', to: 'forms#wizards', as: :forms_wizards
  get 'forms/bootstrap_editors',
      to: 'forms#bootstrap_editors',
      as: :forms_bootstrap_editors
  get 'forms/dropzone', to: 'forms#dropzone', as: :forms_dropzone
  get 'forms/image_cropping',
      to: 'forms#image_cropping',
      as: :forms_image_cropping
  get 'forms/ck_editor', to: 'forms#ck_editor', as: :forms_ck_editor

  # UI Elements
  get 'ui_elements/general_elements',
      to: 'ui_elements#general_elements',
      as: :ui_elements_general_elements
  get 'ui_elements/buttons', to: 'ui_elements#buttons', as: :ui_elements_buttons
  get 'ui_elements/icons/font_awesome',
      to: 'ui_elements#icons_font_awesome',
      as: :ui_elements_icons_font_awesome
  get 'ui_elements/icons/glyph_icons',
      to: 'ui_elements#icons_glyph_icons',
      as: :ui_elements_icons_glyph_icons
  get 'ui_elements/icons/flags',
      to: 'ui_elements#icons_flags',
      as: :ui_elements_icons_flags
  get 'ui_elements/grid', to: 'ui_elements#grid', as: :ui_elements_grid
  get 'ui_elements/tree_view',
      to: 'ui_elements#tree_view',
      as: :ui_elements_tree_view
  get 'ui_elements/nestable_lists',
      to: 'ui_elements#nestable_lists',
      as: :ui_elements_nestable_lists
  get 'ui_elements/jquery_ui',
      to: 'ui_elements#jquery_ui',
      as: :ui_elements_jquery_ui
  get 'ui_elements/typography',
      to: 'ui_elements#typography',
      as: :ui_elements_typography

  # Widgets
  get 'widgets/', to: 'widgets#index', as: :widgets

  # Cool Features
  get 'cool_features/calendar',
      to: 'cool_features#calendar',
      as: :cool_features_calendar
  get 'cool_features/gmap_skins',
      to: 'cool_features#gmap_skins',
      as: :cool_features_gmap_skins

  # App Views
  get 'app_views/projects', to: 'app_views#projects', as: :app_views_projects
  get 'app_views/blog', to: 'app_views#blog', as: :app_views_blog
  get 'app_views/gallery', to: 'app_views#gallery', as: :app_views_gallery
  get 'app_views/forum_layout_general_view',
      to: 'app_views#forum_layout_general_view',
      as: :app_views_forum_layout_general_view
  get 'app_views/forum_layout_topic_view',
      to: 'app_views#forum_layout_topic_view',
      as: :app_views_forum_layout_topic_view
  get 'app_views/forum_layout_post_view',
      to: 'app_views#forum_layout_post_view',
      as: :app_views_forum_layout_post_view
  get 'app_views/profile', to: 'app_views#profile', as: :app_views_profile
  get 'app_views/timeline', to: 'app_views#timeline', as: :app_views_timeline
  get 'app_views/search_page',
      to: 'app_views#search_page',
      as: :app_views_search_page

  # E-Commerce
  get 'e_commerce/orders', to: 'e_commerce#orders', as: :e_commerce_orders
  get 'e_commerce/products_view',
      to: 'e_commerce#products_view',
      as: :e_commerce_products_view
  get 'e_commerce/products_detail',
      to: 'e_commerce#products_detail',
      as: :e_commerce_products_detail

  # Miscellaneous
  get 'miscellaneous/pricing_tables',
      to: 'miscellaneous#pricing_tables',
      as: :miscellaneous_pricing_tables
  get 'miscellaneous/invoice',
      to: 'miscellaneous#invoice',
      as: :miscellaneous_invoice
  get 'miscellaneous/login',
      to: 'miscellaneous#login',
      as: :miscellaneous_login
  get 'miscellaneous/register',
      to: 'miscellaneous#register',
      as: :miscellaneous_register
  get 'miscellaneous/forgot_password',
      to: 'miscellaneous#forgot_password',
      as: :miscellaneous_forgot_password
  get 'miscellaneous/locked_screen',
      to: 'miscellaneous#locked_screen',
      as: :miscellaneous_locked_screen
  get 'miscellaneous/error_404',
      to: 'miscellaneous#error_404',
      as: :miscellaneous_error_404
  get 'miscellaneous/error_500',
      to: 'miscellaneous#error_500',
      as: :miscellaneous_error_500
  get 'miscellaneous/blank_page',
      to: 'miscellaneous#blank_page',
      as: :miscellaneous_blank_page

  # Smart chat API
  get 'smart_chat_api/',
      to: 'smart_chat_api#index',
      as: :smart_chat_api

  # Misc methods
  get '/home/set_locale', to: 'home#set_locale', as: :home_set_locale

  # CK editor
  mount Ckeditor::Engine => '/ckeditor'
end

WB0573SK0/SmartAdmin-1.9.6.1-legacy-86d1c1fa398a/DEVELOPER/BS3/RubyOnRails/full/app/views/layouts/_footer.html.erb
<div class="page-footer">
  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <span class="txt-color-white">SmartAdmin 1.8.x <span class="hidden-xs"> - Web Application Framework</span> © 2014-2015</span>
    </div>

    <div class="col-xs-6 col-sm-6 text-right hidden-xs">
      <div class="txt-color-white inline-block">
        <i class="txt-color-blueLight hidden-mobile">Last account activity <i class="fa fa-clock-o"></i> <strong>52 mins ago &nbsp;</strong> </i>
        <div class="btn-group dropup">
          <button class="btn btn-xs dropdown-toggle bg-color-blue txt-color-white" data-toggle="dropdown">
            <i class="fa fa-link"></i> <span class="caret"></span>
          </button>
          <ul class="dropdown-menu pull-right text-left">
            <li>
              <div class="padding-5">
                <p class="txt-color-darken font-sm no-margin">Download Progress</p>
                <div class="progress progress-micro no-margin">
                  <div class="progress-bar progress-bar-success" style="width: 50%;"></div>
                </div>
              </div>
            </li>
            <li class="divider"></li>
            <li>
              <div class="padding-5">
                <p class="txt-color-darken font-sm no-margin">Server Load</p>
                <div class="progress progress-micro no-margin">
                  <div class="progress-bar progress-bar-success" style="width: 20%;"></div>
                </div>
              </div>
            </li>
            <li class="divider"></li>
            <li>
              <div class="padding-5">
                <p class="txt-color-darken font-sm no-margin">Memory Load <span class="text-danger">*critical*</span></p>
                <div class="progress progress-micro no-margin">
                  <div class="progress-bar progress-bar-danger" style="width: 70%;"></div>
                </div>
              </div>
            </li>
            <li class="divider"></li>
            <li>
              <div class="padding-5">
                <button class="btn btn-block btn-default">refresh</button>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

WB0573SK0/SmartAdmin-1.9.6.1-legacy-86d1c1fa398a/DEVELOPER/BS3/RubyOnRails/full/app/views/layouts/_header.html.erb
<header id="header">
  <div id="logo-group">

    <!-- PLACE YOUR LOGO HERE -->
    <span id="logo"> <%= image_tag 'logo.png', alt: 'SmartAdmin' %> </span>
    <!-- END LOGO PLACEHOLDER -->

    <% if current_user && !@simulate_no_user %>
      <!-- Note: The activity badge color changes when clicked and resets the number to 0
      Suggestion: You may want to set a flag when this happens to tick off all checked messages / notifications -->
      <span id="activity" class="activity-dropdown"> <i class="fa fa-user"></i> <b class="badge"> 21 </b> </span>

      <!-- AJAX-DROPDOWN : control this dropdown height, look and feel from the LESS variable file -->
      <div class="ajax-dropdown">

        <!-- the ID links are fetched via AJAX to the ajax container "ajax-notifications" -->
        <div class="btn-group btn-group-justified" data-toggle="buttons">
          <label class="btn btn-default">
            <input type="radio" name="activity" id="<%= ajax_notify_mail_path %>">
            <%= _('Msgs') %> (14) </label>
          <label class="btn btn-default">
            <input type="radio" name="activity" id="<%= ajax_notify_notifications_path %>">
            <%= _('notify') %> (3) </label>
          <label class="btn btn-default">
            <input type="radio" name="activity" id="<%= ajax_notify_tasks_path %>">
            <%= _('Tasks') %> (4) </label>
        </div>

        <!-- notification content -->
        <div class="ajax-notifications custom-scroll">

          <div class="alert alert-transparent">
            <h4>Click a button to show messages here</h4>
            This blank page message helps protect your privacy, or you can show the first message here automatically.
          </div>

          <i class="fa fa-lock fa-4x fa-border"></i>

        </div>
        <!-- end notification content -->

        <!-- footer: refresh area -->
            <span> Last updated on: 12/12/2013 9:43AM
              <button type="button" data-loading-text="<i class='fa fa-refresh fa-spin'></i> Loading..." class="btn btn-xs btn-default pull-right">
                <i class="fa fa-refresh"></i>
              </button>
            </span>
        <!-- end footer -->

      </div>
      <!-- END AJAX-DROPDOWN -->
    <% end %>
  </div>
  <%= yield :top_right %>

  <% if current_user && !@simulate_no_user %>
    <!-- projects dropdown -->
    <div class="project-context hidden-xs">

      <span class="label">Projects:</span>
      <span class="project-selector dropdown-toggle" data-toggle="dropdown"><%= _('Recent projects') %> <i class="fa fa-angle-down"></i></span>

      <!-- Suggestion: populate this list with fetch and push technique -->
      <ul class="dropdown-menu">
        <li>
          <a href="javascript:void(0);">Online e-merchant management system - attaching integration with the iOS</a>
        </li>
        <li>
          <a href="javascript:void(0);">Notes on pipeline upgradee</a>
        </li>
        <li>
          <a href="javascript:void(0);">Assesment Report for merchant account</a>
        </li>
        <li class="divider"></li>
        <li>
          <a href="javascript:void(0);"><i class="fa fa-power-off"></i> Clear</a>
        </li>
      </ul>
      <!-- end dropdown-menu-->

    </div>
    <!-- end projects dropdown -->

    <!-- pulled right: nav area -->
    <div class="pull-right">

      <!-- collapse menu button -->
      <div id="hide-menu" class="btn-header pull-right">
        <span> <a href="javascript:void(0);" data-action="toggleMenu" title="Collapse Menu"><i class="fa fa-reorder"></i></a> </span>
      </div>
      <!-- end collapse menu -->

      <!-- #MOBILE -->
      <!-- Top menu profile link : this shows only when top menu is active -->
      <ul id="mobile-profile-img" class="header-dropdown-list hidden-xs padding-5">
        <li class="">
          <a href="#" class="dropdown-toggle no-margin userdropdown" data-toggle="dropdown">
            <%= image_tag 'avatars/sunny.png', alt: 'John Doe', class: 'online' %>
          </a>
          <ul class="dropdown-menu pull-right">
            <li>
              <a href="javascript:void(0);" class="padding-10 padding-top-0 padding-bottom-0"><i class="fa fa-cog"></i> Setting</a>
            </li>
            <li class="divider"></li>
            <li>
              <a href="profile.html" class="padding-10 padding-top-0 padding-bottom-0"> <i class="fa fa-user"></i> <u>P</u>rofile</a>
            </li>
            <li class="divider"></li>
            <li>
              <a href="javascript:void(0);" class="padding-10 padding-top-0 padding-bottom-0" data-action="toggleShortcut"><i class="fa fa-arrow-down"></i> <u>S</u>hortcut</a>
            </li>
            <li class="divider"></li>
            <li>
              <a href="javascript:void(0);" class="padding-10 padding-top-0 padding-bottom-0" data-action="launchFullscreen"><i class="fa fa-arrows-alt"></i> Full <u>S</u>creen</a>
            </li>
            <li class="divider"></li>
            <li>
              <a href="login.html" class="padding-10 padding-top-5 padding-bottom-5" data-action="userLogout"><i class="fa fa-sign-out fa-lg"></i> <strong><u>L</u>ogout</strong></a>
            </li>
          </ul>
        </li>
      </ul>

      <!-- logout button -->
      <div id="logout" class="btn-header transparent pull-right">
        <span>
          <%= link_to(destroy_user_session_path, title: 'Sign Out', data: {action: 'userLogout', 'logout-msg' => 'You can improve your security further after logging out by closing this opened browser'}) do %>
            <i class="fa fa-sign-out"></i>
          <% end %>
        </span>
      </div>
      <!-- end logout button -->

      <!-- search mobile button (this is hidden till mobile view port) -->
      <div id="search-mobile" class="btn-header transparent pull-right">
        <span> <a href="javascript:void(0)" title="Search"><i class="fa fa-search"></i></a> </span>
      </div>
      <!-- end search mobile button -->

      <!-- input: search field -->
      <form action="<%= app_views_search_page_path %>" class="header-search pull-right">
        <input id="search-fld"  type="text" name="param" placeholder="<%= _('Find reports and more') %>" data-autocomplete='[
            "ActionScript",
            "AppleScript",
            "Asp",
            "BASIC",
            "C",
            "C++",
            "Clojure",
            "COBOL",
            "ColdFusion",
            "Erlang",
            "Fortran",
            "Groovy",
            "Haskell",
            "Java",
            "JavaScript",
            "Lisp",
            "Perl",
            "PHP",
            "Python",
            "Ruby",
            "Scala",
            "Scheme"]'>
        <button type="submit">
          <i class="fa fa-search"></i>
        </button>
        <a href="javascript:void(0);" id="cancel-search-js" title="Cancel Search"><i class="fa fa-times"></i></a>
      </form>
      <!-- end input: search field -->

      <!-- fullscreen button -->
      <div id="fullscreen" class="btn-header transparent pull-right">
        <span> <a href="javascript:void(0);" data-action="launchFullscreen" title="Full Screen"><i class="fa fa-arrows-alt"></i></a> </span>
      </div>
      <!-- end fullscreen button -->

      <!-- #Voice Command: Start Speech -->
      <div id="speech-btn" class="btn-header transparent pull-right hidden-sm hidden-xs">
        <div>
          <a href="javascript:void(0)" title="Voice Command" data-action="voiceCommand"><i class="fa fa-microphone"></i></a>
          <div class="popover bottom"><div class="arrow"></div>
            <div class="popover-content">
              <h4 class="vc-title">Voice command activated <br><small>Please speak clearly into the mic</small></h4>
              <h4 class="vc-title-error text-center">
                <i class="fa fa-microphone-slash"></i> Voice command failed
                <br><small class="txt-color-red">Must <strong>"Allow"</strong> Microphone</small>
                <br><small class="txt-color-red">Must have <strong>Internet Connection</strong></small>
              </h4>
              <a href="javascript:void(0);" class="btn btn-success" onclick="commands.help()">See Commands</a>
              <a href="javascript:void(0);" class="btn bg-color-purple txt-color-white" onclick="$('#speech-btn .popover').fadeOut(50);">Close Popup</a>
            </div>
          </div>
        </div>
      </div>
      <!-- end voice command -->

      <!-- multiple lang dropdown : find all flags in the flags page -->
      <%= render 'layouts/locale_select' %>
      <!-- end multiple lang -->

    </div>
    <!-- end pulled right: nav area -->
  <% end %>

</header>

WB0573SK0/SmartAdmin-1.9.6.1-legacy-86d1c1fa398a/DEVELOPER/BS3/RubyOnRails/full/app/views/layouts/_left_panel.html.erb
<aside id="left-panel">

  <!-- User info -->
  <div class="login-info">
				<span> <!-- User image size is adjusted inside CSS, it should stay as it -->

					<a href="javascript:void(0);" id="show-shortcut" data-action="toggleShortcut">
            <%= image_tag 'avatars/sunny.png', alt: 'me', class: 'online' %>
            <span>
							john.doe
						</span>
            <i class="fa fa-angle-down"></i>
          </a>

				</span>
  </div>
  <!-- end user info -->

  <!-- NAVIGATION : This navigation is also responsive-->
  <nav>
    <!--
    NOTE: Notice the gaps after each icon usage <i></i>..
    Please note that these links work a bit different than
    traditional href="" links. See documentation for details.
    -->

    <ul>
      <%= left_menu %>
      <li class="chat-users top-menu-invisible <%= 'open' if current_page?(smart_chat_api_path)%>">
        <a href="#">
          <i class="fa fa-lg fa-fw fa-comment-o"><em class="bg-color-pink flash animated">!</em></i> <span class="menu-item-parent"><%= _('Smart Chat API') %> <sup><%= _('beta') %></sup></span>
          <% if current_page?(smart_chat_api_path) %>
            <b class="collapse-sign"><em class="fa fa-minus-square-o"></em></b>
          <% else %>
            <b class="collapse-sign"><em class="fa fa-plus-square-o"></em></b>
          <% end %>
        </a>
        <ul style="<%= 'display: block' if current_page?(smart_chat_api_path)%>">
          <li>
            <!-- DISPLAY USERS -->
            <div class="display-users">

              <input class="form-control chat-user-filter" placeholder="Filter" type="text">

              <a href="#" class="usr"
                 data-chat-id="cha1"
                 data-chat-fname="Sadi"
                 data-chat-lname="Orlaf"
                 data-chat-status="busy"
                 data-chat-alertmsg="Sadi Orlaf is in a meeting. Please do not disturb!"
                 data-chat-alertshow="true"
                 data-rel="popover-hover"
                 data-placement="right"
                 data-html="true"
                 data-content='
											<div class="usr-card">
												<%= image_tag 'avatars/5.png', alt: 'Sadi Orlaf' %>
												<div class="usr-card-content">
													<h3>Sadi Orlaf</h3>
													<p>Marketing Executive</p>
												</div>
											</div>
										'>
                <i></i>Sadi Orlaf
              </a>

              <a href="#" class="usr"
                 data-chat-id="cha2"
                 data-chat-fname="Jessica"
                 data-chat-lname="Dolof"
                 data-chat-status="online"
                 data-chat-alertmsg=""
                 data-chat-alertshow="false"
                 data-rel="popover-hover"
                 data-placement="right"
                 data-html="true"
                 data-content='
											<div class="usr-card">
												<%= image_tag 'avatars/1.png', alt: 'Jessica Dolof' %>
												<div class="usr-card-content">
													<h3>Jessica Dolof</h3>
													<p>Sales Administrator</p>
												</div>
											</div>
										'>
                <i></i>Jessica Dolof
              </a>

              <a href="#" class="usr"
                 data-chat-id="cha3"
                 data-chat-fname="Zekarburg"
                 data-chat-lname="Almandalie"
                 data-chat-status="online"
                 data-rel="popover-hover"
                 data-placement="right"
                 data-html="true"
                 data-content='
											<div class="usr-card">
												<%= image_tag 'avatars/3.png', alt: 'Zekarburg Almandalie' %>
												<div class="usr-card-content">
													<h3>Zekarburg Almandalie</h3>
													<p>Sales Admin</p>
												</div>
											</div>
										'>
                <i></i>Zekarburg Almandalie
              </a>

              <a href="#" class="usr"
                 data-chat-id="cha4"
                 data-chat-fname="Barley"
                 data-chat-lname="Krazurkth"
                 data-chat-status="away"
                 data-rel="popover-hover"
                 data-placement="right"
                 data-html="true"
                 data-content='
											<div class="usr-card">
												<%= image_tag 'avatars/4.png', alt: 'Barley Krazurkth' %>
												<div class="usr-card-content">
													<h3>Barley Krazurkth</h3>
													<p>Sales Director</p>
												</div>
											</div>
										'>
                <i></i>Barley Krazurkth
              </a>

              <a href="#" class="usr offline"
                 data-chat-id="cha5"
                 data-chat-fname="Farhana"
                 data-chat-lname="Amrin"
                 data-chat-status="incognito"
                 data-rel="popover-hover"
                 data-placement="right"
                 data-html="true"
                 data-content='
											<div class="usr-card">
												<%= image_tag 'avatars/female.png', alt: 'Farhana Amrin' %>
												<div class="usr-card-content">
													<h3>Farhana Amrin</h3>
													<p>Support Admin <small><i class="fa fa-music"></i> Playing Beethoven Classics</small></p>
												</div>
											</div>
										'>
                <i></i>Farhana Amrin (offline)
              </a>

              <a href="#" class="usr offline"
                 data-chat-id="cha6"
                 data-chat-fname="Lezley"
                 data-chat-lname="Jacob"
                 data-chat-status="incognito"
                 data-rel="popover-hover"
                 data-placement="right"
                 data-html="true"
                 data-content='
											<div class="usr-card">
												<%= image_tag 'avatars/male.png', alt: 'Lezley Jacob' %>
												<div class="usr-card-content">
													<h3>Lezley Jacob</h3>
													<p>Sales Director</p>
												</div>
											</div>
										'>
                <i></i>Lezley Jacob (offline)
              </a>

              <%= link_to 'About the API', smart_chat_api_path, class: 'btn btn-xs btn-default btn-block sa-chat-learnmore-btn' %>

            </div>
            <!-- END DISPLAY USERS -->
          </li>
        </ul>
      </li>
    </ul>
  </nav>


			<span class="minifyme" data-action="minifyMenu">
				<i class="fa fa-arrow-circle-left hit"></i>
			</span>

</aside>

WB0573SK0/SmartAdmin-1.9.6.1-legacy-86d1c1fa398a/DEVELOPER/BS3/RubyOnRails/full/app/views/layouts/_locale_select.html.erb
<% @selected_locale = selected_locale %>
<ul class="header-dropdown-list hidden-xs">
  <li>
    <%= link_to '#', class: 'dropdown-toggle', data: {toggle: 'dropdown'} do %>
      <%= image_tag "blank.gif", class: "flag flag-#{@selected_locale[:flag]}", alt: @selected_locale[:alt_name] %> <span> <%= @selected_locale[:name] %> </span> <i class="fa fa-angle-down"></i>
  <% end %>
    <ul class="dropdown-menu pull-right">
      <% locale_list.each do |locale| %>
        <li class="<%= 'active' if locale[:locale] == @selected_locale[:locale] %>">
          <%= link_to home_set_locale_path(locale: locale[:locale]) do %>
            <%= image_tag "blank.gif", class: "flag flag-#{locale[:flag]}", alt: locale[:alt_name] %> <%= locale[:name] %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </li>
</ul>

WB0573SK0/SmartAdmin-1.9.6.1-legacy-86d1c1fa398a/DEVELOPER/BS3/RubyOnRails/full/app/views/layouts/_scripts.html.erb
<script type="text/javascript">
  $(document).ready(function() {
    pageSetUp();
  })
</script>

WB0573SK0/SmartAdmin-1.9.6.1-legacy-86d1c1fa398a/DEVELOPER/BS3/RubyOnRails/full/app/views/layouts/_tiles.html.erb
<div id="shortcut">
  <ul>
    <li>
      <%= link_to outlook_inbox_path, class: 'jarvismetro-tile big-cubes bg-color-blue' do %>
        <span class="iconbox"> <i class="fa fa-envelope fa-4x"></i> <span>Mail <span class="label pull-right bg-color-darken">14</span></span> </span>
      <% end %>
    </li>
    <li>
      <%= link_to cool_features_calendar_path, class: 'jarvismetro-tile big-cubes bg-color-orangeDark' do %>
        <span class="iconbox"> <i class="fa fa-calendar fa-4x"></i> <span>Calendar</span> </span>
      <% end %>
    </li>
    <li>
      <%= link_to cool_features_gmap_skins_path, class: 'jarvismetro-tile big-cubes bg-color-purple' do %>
        <span class="iconbox"> <i class="fa fa-map-marker fa-4x"></i> <span>Maps</span> </span>
      <% end %>
    </li>
    <li>
      <%= link_to miscellaneous_invoice_path, class: 'jarvismetro-tile big-cubes bg-color-blueDark' do %>
        <span class="iconbox"> <i class="fa fa-book fa-4x"></i> <span>Invoice <span class="label pull-right bg-color-darken">99</span></span> </span>
      <% end %>
    </li>
    <li>
      <%= link_to app_views_gallery_path, class: 'jarvismetro-tile big-cubes bg-color-greenLight' do %>
        <span class="iconbox"> <i class="fa fa-picture-o fa-4x"></i> <span>Gallery </span> </span>
      <% end %>
    </li>
    <li>
      <%= link_to app_views_profile_path, class: 'jarvismetro-tile big-cubes selected bg-color-pinkDark' do %>
        <span class="iconbox"> <i class="fa fa-user fa-4x"></i> <span>My Profile </span> </span>
      <% end %>
    </li>
  </ul>
</div>